name: Circuits Of Imagination
description: Thoughts about computers, programming, the net and the world.
url: http://blog.circuitsofimagination.com
markdown: redcarpet
highlighter: rouge
safe: true
lsi: false
paginate: 5
paginate_path: "page:num"
excerpt_separator: <!--more-->
