name: Circuits Of Imagination
description: Thoughts about computers, programming, the net and the world.
url: http://blog.circuitsofimagination.com
markdown: kramdown
highlighter: rouge
safe: true  
excerpt_separator: "<!--more-->"
paginate: 5
paginate_path: "page:num"  
plugins:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock  
